#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

canCompile || exit 0    # Dynamic code
# Ruta del archivo controlDict
controlDictPath="./system/controlDict"


restore0Dir

runApplication -s ini blockMesh
   
runApplication -s ini $(getApplication) 
    	


runApplication paraview

# ----------------------------------------------------------------- end-of-file
